export {default as MainNavigation} from './Navigation/MainNavigation'
export {default as Banner} from './Banner/Banner'
export {default as ProductsCategories} from './ProductsCategories/ProductsCategories'
export {default as TrendingProducts} from './TrendingProducts/TrendingProducts'
export {default as OrderShop} from './OtherShop/OrderShop'
export {default as Footer} from './Footer/Footer'
export {default as BannerShop} from './BannerShop/BannerShop'
export {default as Categories} from './Categories/Categories'
export {default as ThumbsGallery} from './ThumbGallery/ThumbsGallery'
export {default as ProductDetail} from './ProductDetail/ProductDetail'
export {default as SingleProduct } from './SingleProduct/SingleProduct'
export {default as ProductDescription} from './ProductDescription/ProductDescription'
export {default as RelatedProduct} from './RelatedProduct/RelatedProduct'
export {default as Card} from './Cart/Card'
export {default as ShoppingCart} from './Shopping/ShoppingCart'
export {default as Quantity} from './Quantity/Quantity'
export {default as PriceFormat} from './PriceFormat/PriceFormat'
export {default as CustomerSupport} from './CustomerSupport/CustomerSupport'
export {default as AutForm} from './AuthForm/AuthForm'
export {default as SignUp} from './SignUp/SignUp'
export {default as BillDetails} from './BillDetails/BillDetails'
export {default as YourOrder} from './YourOrder/YourOrder'
export {default as FormBillDetails} from './FormBillDetails/FormBillDetails'
// default components short paths